# Generated by Django 3.1.6 on 2021-02-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200, null=True)),
                ('heading', models.CharField(max_length=200, null=True)),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300, null=True)),
                ('important_note', models.CharField(max_length=100)),
                ('exp_date', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
    ]
